[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/kevinburke/go-git"
  revision = "da65f3cfe562df3928c9fd53b24030389ba00cd7"

[[constraint]]
  branch = "master"
  name = "github.com/equinox-io/equinox"

[[constraint]]
  name = "github.com/kevinburke/bigtext"
  version = "0.2.0"

[[constraint]]
  name = "github.com/kevinburke/go-types"
  version = "0.21.0"

[[constraint]]
  name = "github.com/kevinburke/rest"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/skratchdot/open-golang"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"
